//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterDeneme1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUyeTakip
    {
        public int uyeTakipID { get; set; }
        public Nullable<int> takipEdenID { get; set; }
        public Nullable<int> takipEdilenID { get; set; }
    
        public virtual tblUye tblUye { get; set; }
        public virtual tblUye tblUye1 { get; set; }
    }
}
