//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterDeneme1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUye
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUye()
        {
            this.tblTwit = new HashSet<tblTwit>();
            this.tblTwitFav = new HashSet<tblTwitFav>();
            this.tblUyeTakip = new HashSet<tblUyeTakip>();
            this.tblUyeTakip1 = new HashSet<tblUyeTakip>();
        }
    
        public int uyeID { get; set; }
        public string kullaniciAdi { get; set; }
        public string parola { get; set; }
        public string email { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTwit> tblTwit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTwitFav> tblTwitFav { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUyeTakip> tblUyeTakip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUyeTakip> tblUyeTakip1 { get; set; }
    }
}
